name: algolia_lite
description: Algolia API Client Lite
version: 0.1.0
repository: https://github.com/Aallam/algolia_lite_dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  collection: ^1.17.0
  compute: ^1.0.2
  http: ^0.13.5
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
