name: algolia_lite
description: Dart API client to interact with Algolia, designed for client apps.
version: 0.2.1
repository: https://github.com/Aallam/algolia_lite_dart

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  dio: ^4.0.6
  meta: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
